config/routes.rb
Rails.application.routes.draw do
  resources :my_pages, only: %i[index]
  resources :searches, only: %i[index show create destroy] do
    collection do
      get :favorite_register
      get :favorite_unregister
    end
  end

  resources :works do
    resources :technologies do
      collection do
        delete :reset
      end
      resources :pyramids
      resources :links do
        member do
          get :good_register
          get :good_unregister
        end
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_scope :user do
    root 'users/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/general_sign_in', to: 'users/sessions#general_sign_in'
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/work.rb
class Work < ApplicationRecord
  validates :title, presence: true, length: { maximum: 10 }
  has_many :technologies, dependent: :destroy
  belongs_to :user
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_work, only: %i[show edit update destroy]

  def index
    @active_works = current_user.works.where(active_flag: true)
    @inactive_works = current_user.works.where(active_flag: false)
  end

  def show; end

  def new
    @work = Work.new
  end

  def edit; end

  def create
    @work = Work.new(work_params)
    respond_to do |format|
      if @work.save
        format.html { redirect_to work_url(@work), notice: 'Work' + I18n.t('notice.success.created') }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to work_url(@work), notice: 'Work' + I18n.t('notice.success.updated') }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work' + I18n.t('notice.success.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_work
    @work = Work.find(params[:id])
  end

  def work_params
    params.require(:work).permit(:title, :public_flag, :user_id, :active_flag)
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_with(model: work, local: true) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation" class = "alert alert-danger">
      <h2><%= pluralize(work.errors.count, I18n.t('error.display')) %> <%= I18n.t('error.save') %></h2>
      <ul>
        <% work.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: I18n.t('works.title') %>
  </div>
  <div class="field">
    <%= form.label :public_flag %>
    <%= form.check_box :public_flag %>
  </div>
  <div class="field">
    <%= form.label :active_flag %>
    <%= form.check_box :active_flag %>
  </div>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= form.submit "登録する", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<div class = "edit-link-word">
  <%= link_to I18n.t('show'), @work %> |
  <%= link_to I18n.t('back'), works_path %>
</div>

app/views/works/index.html.erb
<h1>【<%= current_user.name %>】<%= I18n.t('works.display') %></h1>
<p class = "explanation">
  あなたが気になっているキーワードでワークグループを作成してみましょう<br>
  「技術一覧」ボタンで「技術」を登録してください
</p>
<%= link_to I18n.t('works.new'), new_work_path, class: "btn btn-primary" %>
<div class = "active_works">
  <h2><%= I18n.t('works.active') %></h2>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th colspan="1"></th>
        <th><%= I18n.t('works.title') %></th>
        <th><%= I18n.t('works.public_flag') %></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @active_works.each do |active_work| %>
        <tr class = "table-warning">
          <td><%= link_to I18n.t('technologies.index'), work_technologies_path(active_work), class: "btn btn-success" %></td>
          <td><%= active_work.title %></td>
          <td>
            <% if active_work.public_flag == true%>
              <i class="far fa-eye"></i>
            <% else %>
              <i class="far fa-eye-slash"></i>
            <% end %>
          </td>
          <% if current_user == active_work.user %>
            <td><%= link_to I18n.t("show"), work_path(active_work), class: "btn btn-secondary" %></td>
            <td><%= link_to I18n.t('edit'), edit_work_path(active_work), class: "btn btn-warning" %></td>
            <td><%= link_to I18n.t('destroy'), active_work, method: :delete, data: { confirm: I18n.t('confirm.destroy') }, class: "btn btn-danger" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<div class = "inactive_works">
<h2><%= I18n.t('works.inactive') %></h2>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th colspan="1"></th>
        <th><%= I18n.t('works.title') %></th>
        <th><%= I18n.t('works.public_flag') %></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @inactive_works.each do |inactive_work| %>
        <tr class = "table-warning">
          <td><%= link_to I18n.t('technologies.index'), work_technologies_path(inactive_work), class: "btn btn-success" %></td>
          <td><%= inactive_work.title %></td>
          <td>
            <% if inactive_work.public_flag == true%>
              <i class="far fa-eye"></i>
            <% else %>
              <i class="far fa-eye-slash"></i>
            <% end %>
          </td>
          <% if current_user == inactive_work.user %>
            <td><%= link_to I18n.t("show"), work_path(inactive_work), class: "btn btn-secondary" %></td>
            <td><%= link_to I18n.t("edit"), edit_work_path(inactive_work), class: "btn btn-warning" %></td>
            <td><%= link_to I18n.t("destroy"), inactive_work, method: :delete, data: { confirm: I18n.t("confirm.destroy") }, class: "btn btn-danger" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/works/new.html.erb
<h1>I<%= I18n.t('works.new') %></h1>

<%= render 'form', work: @work %>

<%= link_to I18n.t('back'), works_path, class: 'link_word'%>

app/views/works/show.html.erb
<h1><%= I18n.t('works.show') %></h1>
<div class = "show-content">
  <p>
    <strong><%= I18n.t('works.title') %>:</strong>
    <%= @work.title %>
  </p>
  <p>
    <strong><%= I18n.t('works.public_flag') %>:</strong>
    <%= @work.public_flag %>
  </p>
  <div class = "show-link-word">
    <%= link_to I18n.t('show'), @work %> |
    <%= link_to I18n.t('back'), works_path %>
  </div>
</div>