config/routes.rb
Rails.application.routes.draw do
  resources :my_pages, only: %i[index]
  resources :searches, only: %i[index show create destroy] do
    collection do
      get :favorite_register
      get :favorite_unregister
    end
  end

  resources :works do
    resources :technologies do
      collection do
        delete :reset
      end
      resources :pyramids
      resources :links do
        member do
          get :good_register
          get :good_unregister
        end
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_scope :user do
    root 'users/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/general_sign_in', to: 'users/sessions#general_sign_in'
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/link.rb
class Link < ApplicationRecord
  validates :title, presence: true, length: { maximum: 60 }

  belongs_to :technology
  has_many :link_goods, dependent: :destroy
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link, :set_work, :set_technology, only: %i[show edit update destroy]

  def index
    # session[:technology_id] = params[:format]
    @technology = Technology.find(params[:technology_id])
    @work = Work.find(params[:work_id])
    @owner = Technology.find(params[:technology_id]).work.user
    @links = Link.where(technology_id: @technology.id)
  end

  def show; end

  def new
    set_work
    set_technology
    @link = Link.new(technology_id: @technology.id)
  end

  def edit; end

  def create
    set_work
    set_technology
    @link = Link.new(link_params)
    respond_to do |format|
      if @link.save
        format.html { redirect_to work_technology_link_path(@work, @technology, @link), notice: 'Link' + I18n.t('notice.success.created') }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to work_technology_links_path(@work, @technology), notice: 'Link' + I18n.t('notice.success.updated') }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_work
    set_technology
    @link.destroy
    respond_to do |format|
      format.html do
        redirect_to work_technology_links_path(@work, @technology), notice: 'Link' + I18n.t('notice.success.destroyed')
      end
      format.json { head :no_content }
    end
  end

  def good_register
    set_work
    set_technology
    if LinkGood.find_by(user_id: current_user.id, link_id: params[:id])
      redirect_to work_technology_links_path(params[:technology_id])
    else
      LinkGood.create(user_id: current_user.id, link_id: params[:id])
      link = Link.find(params[:id])
      link.update(good_counter: link.link_goods.count)
      good_counter = link[:good_counter]
      redirect_to work_technology_links_path(@work, @technology)
    end
  end

  def good_unregister
    set_work
    set_technology
    if LinkGood.find_by(user_id: current_user.id, link_id: params[:id])
      LinkGood.find_by(user_id: current_user.id, link_id: params[:id]).destroy
      link = Link.find(params[:id])
      link.update(good_counter: link.link_goods.count)
      good_counter = link[:good_counter]
      redirect_to work_technology_links_path(@work, @technology)
    else
      redirect_to work_technology_links_path(@work, @technology)
    end
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def set_work
    @work = Work.find(params[:work_id])
  end

  def set_technology
    @technology = Technology.find(params[:technology_id])
  end

  def link_params
    params.require(:link).permit(:title, :url, :good_counter, :technology_id)
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: [work, technology, link], local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation" class = "alert alert-danger">
      <h2><%= pluralize(link.errors.count, I18n.t("error.display")) %> <%= I18n.t("error.save") %></h2>

      <ul>
        <% link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: I18n.t('links.title') %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, placeholder: I18n.t('links.url') %>
  </div>

    <%= form.hidden_field :technology_id %>

  <div class="actions">
    <%= form.submit "登録する", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1><%= I18n.t('links.edit') %></h1>

<%= render 'form', work: @work, technology: @technology, link: @link %>

<div class = "edit-link-word">
  <%= link_to I18n.t("show"), work_technology_link_path(@link) %> |
  <%= link_to I18n.t("back"), work_technology_links_path %>
</div>

app/views/links/index.html.erb
<h1>【<%= @technology.name %>】<%= I18n.t('links.display') %></h1>

<p class = "explanation">
  この技術を把握するための外部リンクです<br>
  参考になった場合は「いいねボタン」で評価をしてあげましょう
</p>
<% if @owner == current_user %>
  <p><%= link_to "テクノロジー一覧へ戻る",work_technologies_path(@work) %></p>
  <p><%= link_to I18n.t('links.new'), new_work_technology_link_path, class: "btn btn-primary" %></p>
<% end %>

<table class = "table links-table">
  <thead class="thead-dark">
    <tr>
      <th><%= I18n.t('links.title') %></th>
      <th><%= I18n.t('links.url') %></th>
      <th><%= I18n.t('links.good_counter') %></th>
      <% if  @owner == current_user %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr class = "table-warning">
        <td><%= link.title %></td>
        <td><%= link_to "#{link.url}", link.url, target: :_blank, rel: "noopener noreferrer" %></td>
        <td class = "good-column">
          <span class = "good-counter"><%= link.link_goods.count %></span>
          <% unless LinkGood.find_by(user_id: current_user.id, link_id: link.id) %>
            <%= link_to good_register_work_technology_link_path(@work, @technology, link) do %>
              <i class="far fa-thumbs-up good-register"></i>
            <% end %>
          <% else %>
            <%= link_to good_unregister_work_technology_link_path(@work, @technology, link) do %>
              <i class="far fa-thumbs-up good-unregister"></i>
            <% end %>
          <% end %>
        </td>
        <% if current_user == link.technology.work.user %>
          <td><%= link_to I18n.t("show"), work_technology_link_path(@work, @technology, link), class: "btn btn-secondary" %></td>
          <td><%= link_to I18n.t("edit"), edit_work_technology_link_path(@work, @technology, link), class: "btn btn-warning" %></td>
          <td><%= link_to I18n.t("destroy"), work_technology_link_path(@work, @technology, link), method: :delete, data: {confirm: I18n.t("confirm.destroy")}, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/links/new.html.erb
<h1><%= I18n.t('links.new') %></h1>

<%= render 'form', work: @work, technology: @technology, link: @link %>

<%= link_to I18n.t("back"), work_technology_links_path(@work, @technology), class: 'link_word'%>

app/views/links/show.html.erb
<h1><%= I18n.t('links.show') %></h1>

<div class = "show-content">
  <p>
    <strong><%= I18n.t("links.title") %>:</strong>
    <%= @link.title %>
  </p>
  
  <p>
    <strong><%= I18n.t('links.url') %>:</strong>
    <%= link_to "#{@link.url}", @link.url, class: 'link-url' %>
  </p>
  
  <div class = "show-link-word">
    <%= link_to I18n.t("edit"), edit_work_technology_link_path(@work, @technology, @link) %> |
    <%= link_to I18n.t("back"), work_technology_links_path(@work, @technology) %>
  </div>
</div>