config/routes.rb
Rails.application.routes.draw do
  resources :my_pages, only: %i[index]
  resources :searches, only: %i[index show create destroy] do
    collection do
      get :favorite_register
      get :favorite_unregister
    end
  end

  resources :works do
    resources :technologies do
      collection do
        delete :reset
      end
      resources :pyramids
      resources :links do
        member do
          get :good_register
          get :good_unregister
        end
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_scope :user do
    root 'users/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/general_sign_in', to: 'users/sessions#general_sign_in'
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q
  before_action :set_work

  def index
    if @q.conditions.present?
      session[:search_word] = @q.conditions[0].value
      flash.now[:alert] = '検索キーワードに合致しませんでした' if @q.result.first.nil?
    else
      @works = nil
      flash.now[:alert] = '検索キーワードを入力してください'
    end
  end

  def favorite_register
    Favorite.create(user_id: current_user.id, favorite_id: params[:user_id])
    flash.now[:notice] = I18n.t('favorites.register_notice')
    render :index
  end

  def show
    render :index
  end

  def favorite_unregister
    Favorite.where(user_id: current_user.id, favorite_id: params[:user_id]).first&.destroy
    flash.now[:alert] = I18n.t('favorites.unregister_notice')
    render :index
  end

  private

  def set_q
    @q = Work.ransack(params[:q])
  end

  def set_work
    @works = @q.result
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.erb
<h1><%= I18n.t('searches.page') %></h1>
<p class = "explanation">
  気になるワークを検索して他のユーザーが作ったワークの内容を見てみよう！<br>
  気になったユーザーはお気に入り登録もできるよ！
</p>
<%= search_form_for @q, url: searches_path do |f| %>
  <%= f.label :title_cont, I18n.t('works.name') %>
  <%= f.search_field :title_cont, placeholder: "検索キーワード" %>
  <%= f.submit '検索', class: 'btn btn-primary' %>
<% end %>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th><%= I18n.t('works.display') %></th>
      <th><%= I18n.t('users.display') %></th>
      <th><%= I18n.t('favorites.button') %></th>
      <th><%= I18n.t('favorites.display') %></th>
    </tr>
  </thead>
  <tbody class = "search-result-table">
  <% searched_word = @q.conditions.first.value unless @q.conditions.first.nil? %>
    <% if @works.present? %>
      <% @works.each do |work| %>
        <tr class = "table-warning">
          <% work_owner = work.user %>
          <td><%= link_to "#{work.title}", work_technologies_path(work) %></td>
          <td><%= work_owner.name %></td>
          <td>
            <% unless current_user == work_owner %>
              <% if current_user.favorites.find_by(favorite_id: work_owner.id) %>
                <%# お気に入り登録済の場合 %>
                <%= link_to image_tag("hart.png", class:"favorite-button"), favorite_unregister_searches_path(
                  {user_id: work_owner.id, q: {title_cont: searched_word}}
                )
              %>
              <% else %>
                <%# お気に入り未登録の場合 %>
                <%= link_to image_tag("black_hart.png", class:"favorite-button"), favorite_register_searches_path(
                  {user_id: work_owner.id, q: {title_cont: searched_word}}
                )
                %>
              <% end %>
            <% else %>
              <span class = "favorite-button">-</span>
            <% end %>
          </td>
          <td>
            <%= work_owner.favorite.count %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>