config/routes.rb
Rails.application.routes.draw do
  resources :my_pages, only: %i[index]
  resources :searches, only: %i[index show create destroy] do
    collection do
      get :favorite_register
      get :favorite_unregister
    end
  end

  resources :works do
    resources :technologies do
      collection do
        delete :reset
      end
      resources :pyramids
      resources :links do
        member do
          get :good_register
          get :good_unregister
        end
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_scope :user do
    root 'users/sessions#new'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/general_sign_in', to: 'users/sessions#general_sign_in'
    get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }

  has_many :links, dependent: :destroy
  has_many :hierarckies, dependent: :destroy
  has_many :lower_hierarckies, class_name: 'Hierarcky', foreign_key: :lower_technology_id, dependent: :destroy
  has_many :lower_technologies, through: :hierarckies, source: :upper_technology
  has_many :upper_technologies, through: :lower_hierarckies, source: :technology
  belongs_to :work

  accepts_nested_attributes_for :hierarckies,
  reject_if: proc {
    |attributes| attributes['lower_technology_id'].blank?
  },
  allow_destroy: true
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_technology, only: %i[show edit update destroy]

  def index
    @work = Work.find(params[:work_id])
    # @work = Work.find(id: params[:work_id])
    @technologies = @work.technologies.where(basic_flag: false)
    @basic_technologies = @work.technologies.where(basic_flag: true)
  end

  def show
    @work = Work.find(params[:work_id])
    # path = Rails.application.routes.recognize_path(request.referer)
    # session[:before_controller_path] = path[:controller]
  end

  def new
    @work = Work.find(params[:work_id])
    # path = Rails.application.routes.recognize_path(request.referer)
    # session[:before_controller_path] = path[:controller]
    # session[:top_technology_id] = params[:format] if session[:before_controller_path] == 'pyramids'
    @technology = Technology.new(work_id: session[:work_id])
    @technology.hierarckies.build
  end

  def edit
    @work = Work.find(params[:work_id])
    # path = Rails.application.routes.recognize_path(request.referer)
    # session[:before_controller_path] = path[:controller]
    @technology.hierarckies.build
    @technology.hierarckies.build
  end

  def create
    @work = Work.find(params[:work_id])
    @technology = Technology.new(technology_params)
    @technology.work_id = @work.id
    respond_to do |format|
      if @technology.save
        @upper_hierarcky = Hierarcky.new(
          technology_id: params[:technology][:upper_technology_id],
          lower_technology_id: @technology.id
        )
        @upper_hierarcky.save
        format.html { redirect_to work_technologies_path(@work), notice: 'Technology' + I18n.t('notice.success.created') }
        format.json { render :show, status: :created, location: work_id }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @work = Work.find(params[:work_id])
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to work_technologies_path(@work), notice: 'Technology' + I18n.t('notice.success.updated') }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to work_technologies_path(params[:work_id]), notice: 'Technology' + I18n.t('notice.success.destroyed') }
      format.json { head :no_content }
    end
  end

  def reset
    Hierarcky.find(params[:hierarcky_id]).destroy
    redirect_to edit_technology_path(params[:technology_id])
  end

  private

  def set_technology
    @technology = Technology.find(params[:id])
  end

  def technology_params
    params.require(:technology).permit(
      :name,
      :public_flag,
      :work_id,
      :basic_flag,
      hierarckies_attributes: %i[id lower_technology_id technology_id])
  end

  def work_params
    params.require(:work_id)
  end
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_form.html.erb
<%= form_with(model: [@work, @technology], local: true) do |form| %>
  <% if technology.errors.any? %>
    <div id="error_explanation" class = "alert alert-danger">
      <h2><%= pluralize(technology.errors.count, I18n.t('error.display')) %> <%= I18n.t('error.save') %></h2>
      <ul>
        <% technology.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: I18n.t('technologies.name') %>
  </div>

  <div class="field">
    <%= form.label :public_flag %>
    <%= form.check_box :public_flag %>
  </div>

  <div class="field">
    <%= form.label :basic_flag %>
    <%= form.check_box :basic_flag %>
  </div>

  <% if Technology.where(work_id: @work.id).first != nil %>
    <div class="field">
      <%= form.fields_for :hierarckies do |hierarcky| %>
        <p>
          <%= hierarcky.label I18n.t("technologies.low") %>
          <%= hierarcky.select :lower_technology_id, {"該当無し": nil}.merge(Technology.where(work_id: @work.id).pluck(:name, :id).to_h) %>
          <% unless hierarcky.object.id == nil %>
            <%= link_to "リセット", reset_technologies_path({"hierarcky_id": hierarcky.object.id, "technology_id": technology.id}), method: :delete, class: "btn btn-danger" %>
          <% end %>
        </p>
      <% end %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit '登録する', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<h1><%= I18n.t('technologies.edit') %></h1>

<%= render 'form', technology: @technology %>

<div class = "edit-link-word">
  <%= link_to I18n.t("show"), work_technology_path(@work, @technology) %> |
  <%= link_to I18n.t("back"), work_technologies_path(@work) %>
</div>

app/views/technologies/index.html.erb
<h1>【<%= @work.title %>】<%= I18n.t('technologies.display')  %></h1>
<p class = "explanation">
  あなたが持っている「技術」を登録して「ピラミッド構造」を作りましょう!!
</p>
<%= link_to I18n.t('technologies.new'), new_work_technology_path, class: "btn btn-primary" if current_user.works.find_by(id: @work.id) %>

<h2><%= I18n.t('technologies.application') %></h2>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th colspan="1"></th>
      <th><%= I18n.t('technologies.name') %></th>
      <th><%= I18n.t('technologies.public_flag') %></th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @technologies.each do |technology| %>
      <tr class = "table-warning">
        <td><%= link_to I18n.t('pyramids.structure'), work_technology_pyramids_path(@work, technology), class: "btn btn-success" %></td>
        <td><%= technology.name %></td>
        <td>
          <% if technology.public_flag %>
            <i class="far fa-eye"></i>
          <% else %>
            <i class="far fa-eye-slash"></i>
          <% end %>
        </td>
        <td><%= link_to I18n.t("links.display"), work_technology_links_path(@work, technology), class: "btn btn-info" %></td>
        <% if current_user == technology.work.user %>
          <td><%= link_to I18n.t("show"), work_technology_path(@work, technology), class: "btn btn-secondary" %></td>
          <td><%= link_to I18n.t('technologies.edit'), edit_work_technology_path(@work, technology), class: "btn btn-warning" %></td>
          <td><%= link_to I18n.t("destroy"), work_technology_path(@work, technology), method: :delete, data: { confirm: I18n.t("confirm.destroy") }, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h2><%= I18n.t('technologies.basic')  %></h2>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th colspan="1"></th>
      <th><%= I18n.t('technologies.name') %></th>
      <th><%= I18n.t('technologies.public_flag') %></th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @basic_technologies.each do |technology| %>
      <tr class = "table-warning">
        <td><%= link_to I18n.t('pyramids.structure'), work_technology_pyramids_path(@work, technology), class: "btn btn-success" %></td>
        <td><%= technology.name %></td>
        <td>
          <% if technology.public_flag == true %>
            <i class="far fa-eye"></i>
          <% else %>
            <i class="far fa-eye-slash"></i>
          <% end %>
        </td>
        <td><%= link_to I18n.t("links.display"), work_technology_links_path(@work, technology), class: "btn btn-info" %></td>
        <% if current_user == technology.work.user %>
          <td><%= link_to I18n.t("show"), work_technology_path(@work,technology), class: "btn btn-secondary" %></td>
          <td><%= link_to I18n.t('technologies.edit'), edit_work_technology_path(@work, technology), class: "btn btn-warning" %></td>
          <td><%= link_to I18n.t("destroy"), work_technology_path(@work, technology), method: :delete, data: { confirm: I18n.t("confirm.destroy") }, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to I18n.t("back"), work_technologies_path, class: 'link_word'%>

app/views/technologies/show.html.erb
<h1><%= I18n.t('technologies.show') %></h1>

<div class = "show-content">
  <p>
    <strong>Name:</strong>
    <%= @technology.name %>
  </p>

  <p>
    <strong>Public flag:</strong>
    <%= @technology.public_flag %>
  </p>

  <p>
    <strong>lower_technologies:</strong>
    <% @technology.lower_technologies.each do |technology|%>
      <p><%= technology.name %></p>
    <% end %>
  </p>

  <div class = "show-link-word">
    <% if session[:before_controller_path] == 'pyramids' %>
      <%= link_to I18n.t("edit"), edit_technology_path(session[:top_technology_id]) %> |
      <%= link_to I18n.t("back"), pyramids_path(session[:top_technology_id]) %>
    <% else %>
      <%= link_to I18n.t("edit"), edit_work_technology_path(@work, @technology)  %>|
      <%= link_to I18n.t("back"), work_technologies_path(@work) %>
    <% end %>
  </div>
</div>